language: python
python:
- '2.7'
sudo: required

before_install:

cache:
  directories:
  - $HOME/.cache
install:
- pip install -r scripts/pip-deploy.txt
script:
- echo "No test scripts! Developers should create test scripts to be run here"
after_success:
- ./scripts/travis-prepare-deploy.sh
deploy:
- provider: script
  script: ./scripts/travis-deploy.sh
  skip_cleanup: true
  on:
    branch: master
